#!/bin/bash -x

# Vars
export BASE_TARBALL=base-9dfb81c61d590f3a66a72fd2a06636b010c4f3617fa69632d89f04041c1ef70f.tgz

# Setup
cd /tmp

# Install Chef
curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 13.2.20 && rm install.sh

# Download base policy
mkdir -p /tmp/chef-base
curl -LO http://artifacts-backend.s3-website-us-east-1.amazonaws.com/roles/$BASE_TARBALL
tar -C /tmp/chef-base -xzf /tmp/$BASE_TARBALL
rm /tmp/$BASE_TARBALL

# Initial Chef run
cd /tmp/chef-base
sudo chef-client -z